FROM node:24.8.0-alpine

WORKDIR /app

RUN npm install -g json-server@0.17.4

COPY db-step2.json /app/db-step2.json

EXPOSE 4002

CMD ["json-server", "--watch", "db-step2.json", "--port", "4002", "--host", "0.0.0.0"]
